version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  config-server:
    image: jivebreaddev/license-config:latest
    restart: on-failure
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  licensing-service:
    image: jivebreaddev/license:latest
    restart: on-failure
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend
  organization:
    image: jivebreaddev/organization:latest
    restart: on-failure
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

  eureka-server:
    image: jivebreaddev/eureka:latest
    restart: on-failure
    ports:
      - "8070:8070"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gateway-server:
    image: jivebreaddev/spring-gateway
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://config-server:8071"
      EUREKASERVER_URI: "http://eureka-server:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"
networks:
  backend:
    driver: bridge
