spring:
  application:
    name: organization
  config:
    import: "configserver:"  # ???  ???? ??? ????? ??
  cloud:
    config:
      uri: http://config-server:8071 # config ?? ??
      fail-fast: true
  profiles:
    active: dev
