spring:
  application:
    name: spring-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8071 # config 서버 설정
      fail-fast: true


  # 컨피그  서버에서 설정을 가져온다는 표기