spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
  cloud:
    config:
      uri: http://config-server:8071
server:
  port: 8070
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"
