spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  cloud:
    openfeign:
      micrometer:
        enabled: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://zipkin:9411
server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  tracing:
    propagation:
      type: b3
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
